### ISSUE TITLE
Microfusion Breeder cells spawning in as loot; MFBs not actually self charging?

### ISSUE THREAD

**Issue by Kelprunner** [sunset-wasteland/sunset-wasteland#110]
---- Testmerges: ----
Round ID: 124
BYOND Version: 514.1583
Server revision compiled on: 2022-05-30T19:54:03+00:00
Master commit: [979fc7d4e05c464667ce43c3fa4951aa7182952b](https://github.com/sunset-wasteland/sunset-wasteland/commit/979fc7d4e05c464667ce43c3fa4951aa7182952b)
TGS version: 4.16.2
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----

Just check rare item spawns whenever a new round starts.

As for the self charging, just slap it in a chem machine and check the charge time compared to it with a MFC loaded. Might be intended, but disappointing to not have a tiny version of a charged slime core / bluespace reactor cell.

---- Screenshots: ----

![whoops](https://user-images.githubusercontent.com/106592384/171851894-14fad663-81ba-435e-8469-df81c48002e2.PNG)

---- Additional context: ----

Seems to be pretty consistent at the old nuclear plant on the north end of town.

Second part is probably intended with how self-charging weapons work, but worth mentioning in case it isn't. The recharger pistol does actually self-charge over time. Just odd the cell itself doesn't.

**Comment by Kelprunner** [comment]
Forgot to mention, you also can't load MFBs into any other energy weapon I've found. Going by the descriptor text, this is probably intentional. But hey, gotta be thorough!

Speaking of: Tested the AEP7, AER9, the green tipped AER I forget the name of, the Wattz pistol and rifle, the YK-42b pulse rifle, and a laser gatling.

**Comment by UntoldTactics** [comment]
The MFBs were coded to purely be a cell for recharger weapons. Never meant to exist outside of them. That's why it don't work.
