### ISSUE TITLE
Large survival kit have no sprite applied

### ISSUE THREAD

**Issue by NopemanMcHalt** [sunset-wasteland/sunset-wasteland#111]
## Testmerges:

**LOCALHOST TESTING**

BYOND Version: 514.1584
Server revision compiled on: 2022-06-03
Master commit: [4e70f884bab7692bb2bb48dd85f6d1228b6f591a](https://github.com/sunset-wasteland/sunset-wasteland/commit/4e70f884bab7692bb2bb48dd85f6d1228b6f591a)

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:
Attempt to craft empty large survival pouch (requires 10 leather and a workbench), in the crafting menu.

## Screenshots:
![image](https://user-images.githubusercontent.com/36963049/171856294-3e9a2d15-df8a-4ad9-9ca4-b8c1d4818928.png)

## Additional context:
Codediving reveals the item using `icon_state = "survivalkit_triple"`, _**however**_ sprite isn't present in the `icons\obj\storage.dmi`.

**Comment by MrBobCool** [comment]
This was fixed, tested on a local server and crafted a large survival pouch from a workbench, the sprite is there.
