### ISSUE TITLE
Fence gates are "embed" into fence (walls)

### ISSUE THREAD

**Issue by NopemanMcHalt** [sunset-wasteland/sunset-wasteland#112]
## Testmerges:

**LOCALHOST TESTING**

BYOND Version: 514.1584
Server revision compiled on: 2022-06-03
Master commit: [4e70f884bab7692bb2bb48dd85f6d1228b6f591a](https://github.com/sunset-wasteland/sunset-wasteland/commit/4e70f884bab7692bb2bb48dd85f6d1228b6f591a)

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:
Go to the Bighorn, go East to the Trading Shed. Attempt to open fence gates of the (er) trading points, note lower ones.

## Screenshots:
![image](https://user-images.githubusercontent.com/36963049/171858279-1a2778e4-1079-4a93-bda9-e15e3822bbd4.png)
![image](https://user-images.githubusercontent.com/36963049/171858630-4c00a77d-1551-4b57-81aa-a81895113f07.png)

## Additional context:
N/A

**Comment by ExoticJazz** [comment]
Tried opening them by clicking? I know for some reason they don't auto open when you run into them.

**Comment by NopemanMcHalt** [comment]
> Tried opening them by clicking? I know for some reason they don't auto open when you run into them.

They do open by clicking, however due the fact that fence itself is still overlapping the gate you cannot enter/move into it.

**Comment by ExoticJazz** [comment]
Fixed with PR #116
