### ISSUE TITLE
Duplicate equipment duffelbag 

### ISSUE THREAD

**Issue by Troontjelolo** [sunset-wasteland/sunset-wasteland#122]
---- Testmerges: ----
None

---- Reproduction: ----

I selected the sub-role same way as I do every time.

---- Screenshots: ----

![image](https://user-images.githubusercontent.com/56892466/172059639-41778730-47bc-4eda-835a-54e3587791e4.png)

---- Additional context: ----

I was lagging a bit during it, that's about it.

**Comment by ExoticJazz** [comment]
Known long term issue, preferably the entire loadout systems needs a swap to resolve this.
