### ISSUE TITLE
Cannot Play Venator Slot -- Job Slot is Open

### ISSUE THREAD

**Issue by pilotbland** [sunset-wasteland/sunset-wasteland#134]
---- Testmerges: ----
Round ID: 138
BYOND Version: 514.1583
Server revision compiled on: 2022-06-06T16:52:21+00:00
Master commit: [2128228e04b9077bbb0fa5417fe1c89fba242589](https://github.com/sunset-wasteland/sunset-wasteland/commit/2128228e04b9077bbb0fa5417fe1c89fba242589)
TGS version: 4.16.2
DMAPI version: 5.3.0

---- Reproduction: ----
Come to spawn in as a venator, cannot spawn in as a venator. The role doesn't appear in the list whatsoever of roles, I've opened more job slots, I've altered my exemption, (I'm staff regardless, so...) etc etc. There is no way to genuinely play venator at the current moment. It appears in the occupation preferences, but not the jobs list itself.

---- Screenshots: ----
https://i.gyazo.com/5eca9f1c529df450f10944c4cbd4e154.png

---- Additional context: ----

The slot isn't being taken up, I don't think its some sort of... other slot that it's being weird about, best of luck, plz fix.

**Comment by ExoticJazz** [comment]
Fixed with PR #149
