### ISSUE TITLE
UI elements missing, restored when soul is in another body, missing again when returned to original body.

### ISSUE THREAD

**Issue by McRex007** [sunset-wasteland/sunset-wasteland#160]
---- Testmerges: ----

BYOND Version: 514.1583
Server revision compiled on: 2022-06-06T16:52:21+00:00
Master commit: [2128228e04b9077bbb0fa5417fe1c89fba242589](https://github.com/sunset-wasteland/sunset-wasteland/commit/2128228e04b9077bbb0fa5417fe1c89fba242589)
TGS version: 4.16.2
DMAPI version: 5.3.0

---- Reproduction: ----

On all 3 of my characters, the Combat, Sprint, and Jog elements of the HUD are missing. All 3 have heavy sleeper, cold blooded, horrifying tastes quirks and the anthropomorphic lizard species in common. At round end someone used the ginyu captain body swap ability on me, and while in their body, all HUD elements are functioning. Reconnecting does not fix. Clearing cache does not fix. Updating Byond did not fix. This has been the case since I joined and up to this very moment.

When I returned to my original body, the HUD elements were missing again.

---- Screenshots: ----

https://i.imgur.com/lCPFAyt.png

---- Additional context: ----

Midnight, Retro, Plasmafire, Slimecore, Operative and Clockwork have a run/walk button appear. Fallout and Darkout have the sprint button, and the jog button missing, as well as the combat shutter thing.

https://i.imgur.com/Z8SqIsS.png

I am becoming insane in the membrane

**Comment by out-of-phaze** [comment]
Can confirm. This is because DR2 removed the sprint icons from the base UI icon files and then didn't update anything else, so touching your UI prefs *at all* will break it. Fix inbound.
