### ISSUE TITLE
10mm Extended Magazine labelled as "10mm Pistol Extended Magazine" in ammo workbench.

### ISSUE THREAD

**Issue by McRex007** [sunset-wasteland/sunset-wasteland#28]
The 10mm extended magazine is labelled as a 10mm pistol extended magazine in the ammo workbench, but cannot be used in a 10mm pistol. I assume its for balancing reasons, but I don't see anyone ever really using 10mm pistols, so it might benefit diversity if they were allowed to use the extended magazines.

**Comment by ExoticJazz** [comment]
Fixed via PR #55
