### ISSUE TITLE
Discord link on Readme.md has expired

### ISSUE THREAD

**Issue by Allfd** [sunset-wasteland/sunset-wasteland#301]
---- Reproduction: ----

Using a discord account not a member of the discord server, click the invite link on the github readme.

**Comment by WightAndSpirits** [comment]
Bumping this; I'd very much like to join the server but currently have no means to!

**Comment by ExoticJazz** [comment]
Catch us on our hub days during the weekend, we limit discord invites to maintain a controlled flow of incoming players.
