### ISSUE TITLE
Duplicate listing for 9mm Rubber in the ammo bench that produces a single 9mm bullet.

### ISSUE THREAD

**Issue by McRex007** [sunset-wasteland/sunset-wasteland#32]
## Testmerges:

Round ID: 41
BYOND Version: 514.1583
Server revision compiled on: 2022-05-16T03:38:26+00:00
Master commit: [0611d319ba499957a630c10b06d20beff068d09b](https://github.com/sunset-wasteland/sunset-wasteland/commit/0611d319ba499957a630c10b06d20beff068d09b)
TGS version: 4.16.2
DMAPI version: 5.3.0
## Reproduction:

There are two listing for 9mm rubber ammo. One of them is in simple, costs 9000 iron and 900 blackpowder, and produces a box of 30 rubber rounds. The second is is in simple ammo, and costs 1350 blackpowder instead of 900. It will produce a **single** 9mm rubber bullet. Both listings also appear when searching for 9mm rubber.

**Comment by ExoticJazz** [comment]
Fixed via PR #55
