### ISSUE TITLE
Spawning like a Wastelander when playing as NCR trooper.

### ISSUE THREAD

**Issue by Fr3nchFr13s** [sunset-wasteland/sunset-wasteland#320]
As the title suggest, I keep spawning in the various border tunnels of the central map, despite the fact that I chose to play as an NCR trooper. I am unsure whether this also affects other roles that I play.

**Comment by MrBobCool** [comment]
Joined as trooper until the max trooper limit was reached, could not replicate the bug. Joined as every NCR role until they were all filled, could not replicate bug.

My guess is that this was fixed at some point. Likely safe to close.
