### ISSUE TITLE
Mobs aggro to each other without line of sight

### ISSUE THREAD

**Issue by faaaay** [sunset-wasteland/sunset-wasteland#35]
## Testmerges:

None.

> Round ID: 42
> BYOND Version: 514.1583
> Server revision compiled on: 2022-05-16T14:39:06+00:00
> Master commit: [9ad2feb4f467eda4fc44bea4c05db6807bedbb86](https://github.com/sunset-wasteland/sunset-wasteland/commit/9ad2feb4f467eda4fc44bea4c05db6807bedbb86)
> TGS version: 4.16.2
> DMAPI version: 5.3.0
> 
> Current Informational Settings:
> Protect Authority Roles From Traitor: 0
> Protect Assistant Role From Traitor: 0
> Enforce Human Authority: 0
> Allow Latejoin Antagonists: 1

## Reproduction:

Enter the North Bunker northeast of the NCR base. You'll find that several internal doors have already been broken down, and that hostile simplemobs have killed or injured each other. This should not happen, as the mobs do not have a line of sight to each other and thus should not break down opaque doors to fight.

**Comment by ExoticJazz** [comment]
I believe this is intended mob behavior as they have simulated hearing, for example mobs inside buildings can hear your character running past the building so they will attempt to investigate and engage without needing to have spotted you visually first.
