### ISSUE TITLE
Bitters (And possibly Super Stimpacks) don't work under certain circumstances.

### ISSUE THREAD

**Issue by McRex007** [sunset-wasteland/sunset-wasteland#393]
---- Testmerges: ----

Round ID: 485
BYOND Version: 514.1583
Server revision compiled on: 2022-09-02T11:39:09+00:00
Master commit: [deb4abfe1734a753e187ac837453983c78c4c3f1](https://github.com/sunset-wasteland/sunset-wasteland/commit/deb4abfe1734a753e187ac837453983c78c4c3f1)
TGS version: 4.19.0
DMAPI version: 5.3.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----

Crafting bitters in boxes of 5, or possibly something else done with them, causes them to not work. They will not heal any damage. Others have observed it occurring with brute and I've personally experienced it with burns. A sign this has happened might be that you will have 15 bitters left over in one of your beakers.
---- Screenshots: ----

---- Additional context: ----

I've been told it happens with super stimpacks too. It might happen because of alchemy racks, or chem fridges. I can't say for sure. Happens to both people who benefit from the extra healing of bitters and those who don't and suffer hallucinations.

**Comment by out-of-phaze** [comment]
This is because of server load/lag and occurs intermittently. Recent updates should make it happen less often.
