### ISSUE TITLE
Reloading Benches do not print .22 Rubber (also invisible boxes)

### ISSUE THREAD

**Issue by Planetary-ae** [sunset-wasteland/sunset-wasteland#46]
---- Testmerges: ----

Round ID: 54
BYOND Version: 514.1583
Server revision compiled on: 2022-05-18T18:31:02+00:00
Master commit: [a48f80a1bceb9854df3c066e92862f2f6186dc65](https://github.com/sunset-wasteland/sunset-wasteland/commit/a48f80a1bceb9854df3c066e92862f2f6186dc65)
TGS version: 4.16.2
DMAPI version: 5.3.0

---- Reproduction: ----
Get a reloading bench.
Under 'Basic' ammo try and print .22lr and .22 Rubber
The bench prints boxes of .22lr for both options, no rubber. The boxes are also invisible.

**Comment by ExoticJazz** [comment]
Fixed via PR #55
