### ISSUE TITLE
Ranger frequency doesnt seem to work

### ISSUE THREAD

**Issue by Spartan2548** [sunset-wasteland/sunset-wasteland#51]
---- Testmerges: ----

---- Reproduction: ----

---- Screenshots: ----

---- Additional context: ----

**Comment by ExoticJazz** [comment]
Possibly same situation as Town and Khan frequencies not working. Latter of which is currently on the temporary SS13 Security frequency.

**Comment by ExoticJazz** [comment]
Fix introduced with PR #115
