### ISSUE TITLE
PAX doesn't prevent wattz rifle firing

### ISSUE THREAD

**Issue by DiscordWizard** [sunset-wasteland/sunset-wasteland#526]
---- Testmerges: ----

---- Reproduction: ----

(No testmerge info cause this was a while ago and I've forgotten the round, sorry)
During tests with baghead at the town, I was paxed and asked to shoot him.
Using a normal rifle gave me the message "This weapon is loaded with lethals, it may hurt someone" and didn't fire
With a wattz 2000e (Haven't tested with any other energy weapons) it simply shot the man, while I still had pax in my system

---- Screenshots: ----

---- Additional context: ----

**Comment by MrBobCool** [comment]
Wasn't able to reproduce this bug, are you sure you didn't metabolize all the pax by the time you tried to fire the wattz 2000e?
![pax](https://user-images.githubusercontent.com/40435661/196433554-dd7a8438-829e-444f-8f8c-bd3cff8444d1.png)
