### ISSUE TITLE
Sabitsuki haircut doesn't work, my favorite.

### ISSUE THREAD

**Issue by pilotbland** [sunset-wasteland/sunset-wasteland#60]
---- Testmerges: ----
?

---- Reproduction: ----
Pick the Sabitsuki haircut. See an error in it's place.

---- Screenshots: ----

https://i.gyazo.com/d2a748481b8b0e19533faef95add65c3.png

---- Additional context: ----

I've got the functioning DMI if need be?

**Comment by ExoticJazz** [comment]
Feel free to send me the missing asset and I'll add it.

Also for future reference, the testmerge section seeks
![image](https://user-images.githubusercontent.com/8015239/169699150-f5a16959-5b3c-4e83-9d13-4c736c67b0da.png)
