### ISSUE TITLE
"Observe" and "Jump to Mob" list have duplicated names

### ISSUE THREAD

**Issue by NopemanMcHalt** [sunset-wasteland/sunset-wasteland#62]
## Testmerges:

None.

## Reproduction:
When as ghost, click on "Observe" or "Jump to Mob" command (or press Jump to mob icon on HUD). Scroll down until you find player character names.

## Screenshots:
![image](https://user-images.githubusercontent.com/36963049/169711300-71c7828c-d46d-4355-b135-47ded12e9b98.png)
![image](https://user-images.githubusercontent.com/36963049/169711316-7e951714-dec3-438c-a9b3-9c644ae42f79.png)

## Additional context:

Same issue could be found in similar codebases, albeit in a lesser extent unlike here.

**Comment by AmethystTheSergal** [comment]
This seems to be the case that the 'observe' and 'jump to mob' verbs were replaced with the 'Orbit' function in the ghost tab. They were just apparently left-over residue.
