### ISSUE TITLE
Pistol Template go brrrr

### ISSUE THREAD

**Issue by AmethystTheSergal** [sunset-wasteland/sunset-wasteland#69]
![Pistolwtf](https://user-images.githubusercontent.com/52103820/170228820-583d5805-3ff4-4b1c-802e-965cc3ee1f51.PNG)

Seems like a template wormed its way into a locker. Those naughty templates!

**Comment by ExoticJazz** [comment]
Been seeing these for a long while for various weapon categories, possibly a false item in the spawner's list.

**Comment by AmethystTheSergal** [comment]
> Been seeing these for a long while for various weapon categories, possibly a false item in the spawner's list.

I believe occulus (eris codebase server) had these show up from time to time. I don't know how they removed them, though.
