### ISSUE TITLE
R82 BP BROKEN!!!

### ISSUE THREAD

**Issue by WormEnthusiast** [sunset-wasteland/sunset-wasteland#779]
---- Testmerges: ----
???

---- Reproduction: ----
Acquire BP
Read BP
BP Doesn't Give R82 Crafting Recipe

Do be aware that I was doing this as Outlaw with the Raider Smith class and starter books, it's either a broken BP or a weird set of circumstances, if it is that then I'm sorry.

**Comment by CDRDecky** [comment]
Could not replicate the issue. 
The blueprint was spawned, read, and the crafting recipe was properly given and able to be crafted.
